##############################################################################
# Application continuous deployment worflow :
# - runs manually,
# - docker build the app image and push it to registry.
# - restart Azure App Service
##############################################################################

name: App Deploy
run-name: App Deploy run (${{ github.event_name }} by ${{ github.actor }})

# Variables
env:
  DOCKER_IMAGE_NAME: sebez/poc
  DOCKER_IMAGE_VERSION: 1.0.0.0

# Run deploy manually
on:
  workflow_dispatch:
    # TODO put in GitHub secrets.
    inputs:
      # Docker registry
      dockerRegistry:
        description: Docker registry name
        required: true
        type: string
        default: sebezpoc.azurecr.io

      # Docker registry user
      dockerUser:
        description: Docker registry user
        required: true
        type: string

      # Docker registry secret
      dockerSecret:
        description: Docker registry secret
        required: true
        type: string

jobs:
  # Docker build job
  docker-build-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      # Check out sources
      - name: Check out sources of ${{ github.ref }}
        uses: actions/checkout@v3

      # Docker login
      - name: Docker login
        run: docker login -u ${{ inputs.dockerUser }} -p ${{ inputs.dockerSecret }}

      # Docker build
      - name: Docker login
        run: docker build . --file Dockerfile --tag ${{ inputs.dockerRegistry }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION

      # Docker push
      - name: Docker push
        run: docker push ${{ inputs.dockerRegistry }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
